version: '2'
services:
  www-data:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./www-data/log/:/var/log/nginx/
      - ./www-data/nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /usr/share/nginx/html
    networks:
      nginx-varnish-ci:
        aliases:
          - www-data.nginx-varnish.ci

  varnish:
    image: varnish:latest
    ports:
      - "80:80"
    volumes:
      - ./varnish:/etc/varnish
    depends_on:
      - www-data
    networks:
      nginx-varnish-ci:
        aliases:
          - varnish.nginx-varnish.ci

networks:
  nginx-varnish-ci:
    driver: bridge
